name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@master
        with:
          stale-issue-message: 'Auto closed. If the main workflow does not work properly, please send an email to snwcreations@qq.com !'
          days-before-stale: 0
          days-before-close: 0
